### ISSUE TITLE
String with "/_do_not_use" appears in Create3 namespace after configuring discovery server

### ISSUE THREAD

**Issue by Fingerling42** [turtlebot/turtlebot4_setup#13]
### Robot Model

Turtlebot4 Standard

### ROS distro

Humble

### Networking Configuration

Discovery Server

### OS

Ubuntu 22.04

### Built from source or installed?

Installed

### Package version

Package: ros-humble-turtlebot4-setup
Version: 1.0.4-1jammy.20240704.075434

### Expected behaviour

The `turtlebot-setup` tool successfully configures discovery server.

### Actual behaviour

After updating the packages on the robot, I tried to configure the discovery server on RaspPi using the `turtlebot-setup` tool. The setup was successful, however, not all topics from Create3 became visible on RaspPi.

After digging through the Create3 settings, I noticed that the line `/_do_not_use` appeared in the namespace. After removing it and restarting, everything worked.

![image](https://github.com/user-attachments/assets/940f5610-7e46-49c7-8ccf-8c4eac44b6ea)

### Error messages

```bash
No error messages
```

### To Reproduce

1. Complete configuring discovery server via `turtlebot-setup` tool
2. Open Create 3 UI
3. Check namespace
4. See that not all topics are visible on RaspPi via `ros2 topic list`

**Comment by Fingerling42** [comment]
**Upd**: Also, I tried adding a namespace to use two robots, and now the actions list shows duplicate actions with an extra line in the namespace:
![image](https://github.com/user-attachments/assets/8e899c43-9371-47c1-8c13-9a6be76adb5b)

**Comment by hilary-luo** [comment]
Since you are using the version that is only available on the ROS 2 test server or from source then you need to use the documentation found in this PR: https://github.com/turtlebot/turtlebot4-user-manual/pull/22

This documentation update will be released when the packages are openly available on the ROS 2 servers.

This new updated package has significant performance upgrades and the ability to do multi-robot discovery server. However, if you are using the updated turtlebot4_setup tool then you must also use the updated turtlebot4_robot package. The namespacing that you have described was necessary to provide this functionality. Please ensure you have both packages updated to the latest follow what is indicated by not using any of the topics/actions/services that include the "_do_not_use" namespace. See the linked PR for the full documentation on how the updated software works including how to choose which create3 topics are exposed.

**Comment by Fingerling42** [comment]
Ok, I get it, I'll look at this documentation.

The only thing is that I definitely didn't build the version from sources. The situation described at the beginning of the issue arose after updating via apt-get. I'm not sure about the test server either, especially since both Turtlebots behave this way after the update. I'll check it.

**UPD**: 
Yes, indeed, both robots had test servers.

**Comment by Fingerling42** [comment]
With that, I'll close this issue. For those who buy pre-built and pre-installed Turtlebot, please pay attention which ROS server is listed in apt.
